### ISSUE TITLE
Craft a sample that shows how to use AutoComplete feature from TextBox

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/documentation#110]
- [x] Drop current sample in Showcases https://github.com/RadicalFx/documentation/pull/117
- [x] New sample: https://github.com/RadicalFx/documentation/pull/118

**Comment by mauroservienti** [comment]
@ucollina82 the sample should be a standalone sample and not included in the showcases application. Create a new solution like the Plugins or Modules ones: https://github.com/RadicalFx/documentation/tree/master/samples

**Comment by ucollina82** [comment]
Can I create a generic solution for all other possible examples with the name "StandaloneSamples ..." or is it better to create a specification with the name "Autocomplete ..."?

**Comment by mauroservienti** [comment]
I'd say one solution per sample, such as AutocompleteSample. No documentation is needed at this time.
