### ISSUE TITLE
docs migration

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/documentation#2]
[GitBook](https://www.gitbook.com/book/radicalfx/documentation) is a good compromise. The source of truth is still this repo, changes can be made here or in GitBook directly and there will be a 2 way sync.

Documentation is a available here: https://docs.radicalframework.com/

Keeping track of migration progress is here is not easy. So I decided to delete pages from the [Wiki](https://github.com/RadicalFx/Radical/wiki) as they are migrated to GitBook.

**Comment by mauroservienti** [comment]
doc migrated from [Wiki](https://github.com/RadicalFx/radical/wiki) to [Read the docs](http://docs.radicalframework.com/en/import-from-wiki/) (actually on a dedicated `import` branch)

All the pages need a full review

**Comment by nazarenomanco** [comment]
@mauroservienti do you need an extra pair of eyes? :eyes:

**Comment by mauroservienti** [comment]
Sooner or later yes, the migration process is a nightmare, what would be interesting to do is:

* Some pages had been migrated here: http://docs.radicalframework.com/en/latest/
* Go through migrated pages and
    * check in the above list what is migrated regardless of the quality
    * raise issues if something is wrong in the [doco repo](https://github.com/RadicalFx/documentation/issues)

Once we are aligned we can start migrating all what remains

**Comment by mauroservienti** [comment]
I decided to delete the ReadTheDocs project and go ahead with a simple GitHub pages site.

**Comment by mauroservienti** [comment]
I changed my mind once again, finding the right tool is a nightmare. Using a bare Jekyll/GitHub pages site is a nightmare because building the TOC is super complex and a maintenance pain.
Seems that [GitBook](https://www.gitbook.com/book/radicalfx/documentation) is a good compromise. The source of truth is still this repo, changes can be made here or in GitBook directly and there will be a 2 way sync.
Documentation is a available here: https://docs.radicalframework.com/
