### ISSUE TITLE
Evaluate read the docs as hosting service

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/documentation#40]
While investigating other things I discovered that Read The Docs support for markdown has improved. The `read-the-docs` branch contains some experiments.

**Comment by mauroservienti** [comment]
http://radical-documentation.readthedocs.io/en/read-the-docs/

**Comment by mauroservienti** [comment]
Migrated all docs to Read the Docs: http://radical-documentation.readthedocs.io/en/read-the-docs/

Pros:
* much much faster than GitBook
* broken links detection at build time (this is a big plus)

Cons:
* Limited ToC functionalities
* Less customization options

I'm 👍 for the migration to Read the Docs. Things left to do:

* Add you both to Read the Docs project
* Discover how to add a `contribute via GitHub` button to allow easy online edits of pages
* merge to master overriding current documentation
* Add domain configuration to Read the Docs settings so to be hosted at `docs.radicalframework.com`
* change DNS CNAME settings in CloudFlare to point to `readthedocs.io`
* Verify CloudFlare CDN + SSL settings don't break doco

@nazarenomanco @micdenny thoughts?

**Comment by micdenny** [comment]
here's my 2 cent:

- probably gitbook has a better UI design, but yes the performance sometimes are really really bad.
- the `contribute via GitHub` button would be a really important feature ([topshelf docs has this feature](https://topshelf.readthedocs.io/en/latest/installation/install.html))

what about DocFX that uses MS to generate [this kind of docs](https://docs.microsoft.com/en-us/dotnet/core/get-started)? that can be used also to generate the reference from the triple-slash comments to link from the tutorial also the class docs. But I have several concerns about that: could be built also from appveyor? ([the answer seems to be yes it can](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#4-use-docfx-with-a-build-server)) can we easily stole MS template? How hard it is?

told this, I like the porting to read the docs 👍

**Comment by mauroservienti** [comment]
O, closing in favor of #51
