### ISSUE TITLE
Complete migration to Read the Docs

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/documentation#51]
Spun off from #40 

## PoA

* [ ] Discover how to add a `contribute via GitHub` button to allow easy online edits of pages
* [x] Add @micdenny to Read the Docs as maintainer
* [x] Add @nazarenomanco to Read the Docs as maintainer
* [ ] merge to master overriding current documentation
* [ ] Add domain configuration to Read the Docs settings so to be hosted at `docs.radicalframework.com`
* [ ] change DNS CNAME settings in CloudFlare to point to `readthedocs.io`
* [ ] Verify CloudFlare CDN + SSL settings don't break doco

**Comment by mauroservienti** [comment]
@nazarenomanco @micdenny can you create a Read the Docs account, you can login via GitHub, and ping here listing your Read the Docs username so that I can add you both as admins?

**Comment by nazarenomanco** [comment]
@mauroservienti mine is `nazareno`

**Comment by mauroservienti** [comment]
I’ve been testing GitBook perf for the last few weeks. Since the migration to the new platform it’s much faster than before. I’m hesitant to go on investing in this. Moving back to the backlog to reevaluate in the future.

**Comment by mauroservienti** [comment]
GitBook lately is blazing fast. There is no point in investing time in migrating to something else. Withdrawing this as not needed.
